# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_client(object):
    def setupUi(self, client):
        client.setObjectName("client")
        client.resize(521, 311)
        client.setMinimumSize(QtCore.QSize(521, 311))
        client.setMaximumSize(QtCore.QSize(521, 311))
        self.data_text = QtWidgets.QTextEdit(client)
        self.data_text.setGeometry(QtCore.QRect(20, 80, 481, 181))
        self.data_text.setObjectName("data_text")
        self.horizontalLayoutWidget = QtWidgets.QWidget(client)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(19, 270, 481, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.exit_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.exit_btn.setFont(font)
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(client)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 481, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.ip_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.ip_text.setObjectName("ip_text")
        self.horizontalLayout_2.addWidget(self.ip_text)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.port_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.port_text.setObjectName("port_text")
        self.horizontalLayout_2.addWidget(self.port_text)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.send_text = QtWidgets.QLineEdit(client)
        self.send_text.setGeometry(QtCore.QRect(70, 50, 361, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.send_text.setFont(font)
        self.send_text.setText("")
        self.send_text.setObjectName("send_text")
        self.label_3 = QtWidgets.QLabel(client)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 51, 21))
        self.label_3.setObjectName("label_3")
        self.send_btn = QtWidgets.QPushButton(client)
        self.send_btn.setGeometry(QtCore.QRect(440, 50, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.send_btn.setFont(font)
        self.send_btn.setObjectName("send_btn")

        self.retranslateUi(client)
        QtCore.QMetaObject.connectSlotsByName(client)

    def retranslateUi(self, client):
        _translate = QtCore.QCoreApplication.translate
        client.setWindowTitle(_translate("client", "Form"))
        self.exit_btn.setText(_translate("client", "退出"))
        self.label.setText(_translate("client", "<html><head/><body><p><span style=\" font-size:12pt;\">host:</span></p></body></html>"))
        self.label_2.setText(_translate("client", "<html><head/><body><p><span style=\" font-size:12pt;\">port:</span></p></body></html>"))
        self.label_3.setText(_translate("client", "<html><head/><body><p><span style=\" font-size:12pt;\">send:</span></p></body></html>"))
        self.send_btn.setText(_translate("client", "send"))
