# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history_alarm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_history_alarm(object):
    def setupUi(self, history_alarm):
        history_alarm.setObjectName("history_alarm")
        history_alarm.resize(472, 662)
        self.tableView = QtWidgets.QTableView(history_alarm)
        self.tableView.setGeometry(QtCore.QRect(10, 80, 451, 491))
        self.tableView.setObjectName("tableView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(history_alarm)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 471, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(history_alarm)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 600, 471, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)

        self.retranslateUi(history_alarm)
        QtCore.QMetaObject.connectSlotsByName(history_alarm)

    def retranslateUi(self, history_alarm):
        _translate = QtCore.QCoreApplication.translate
        history_alarm.setWindowTitle(_translate("history_alarm", "异常报警历史记录"))
        self.label.setText(_translate("history_alarm", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">异常报警历史记录</span></p></body></html>"))
        self.pushButton.setText(_translate("history_alarm", "退出"))
