# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(563, 329)
        MainWindow.setStyleSheet("background-image:url(:/新前缀/welcome.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 711, 61))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background:rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 300, 111, 31))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 60, 571, 311))
        self.label_4.setStyleSheet("background-image:url(:/new/welcome_3.gif);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 30, 321, 61))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-200, 0, 221, 61))
        self.label_5.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600; font-style:italic; color:#ffffff;\">    档案室环境监测系统</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; font-style:italic; text-decoration: underline; color:#00e5e5;\">V1.0.0</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;\">A</span><span style=\" font-size:11pt; font-style:italic; text-decoration: underline; color:#ffffff;\">rchives</span><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;\">E</span><span style=\" font-size:11pt; font-style:italic; text-decoration: underline; color:#ffffff;\">nvironmental</span><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;\">M</span><span style=\" font-size:11pt; font-style:italic; text-decoration: underline; color:#ffffff;\">onitoring</span><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;\">S</span><span style=\" font-size:11pt; font-style:italic; text-decoration: underline; color:#ffffff;\">ystem</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
import Resource_files.photo_rc
